import { notFound } from "next/navigation";
import { MembershipRole, Role } from "@prisma/client";
import { db } from "@/lib/db";
import { getCurrentUser } from "@/lib/current-user";
import { createPost, joinGroup, leaveGroup } from "@/app/actions";
import { Notice, PostCard } from "@/components/ui";
export default async function GroupPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ error?: string }> }) {
  const { slug } = await params, { error } = await searchParams, user = await getCurrentUser();
  const group = await db.group.findUnique({ where: { slug }, include: { venue: true, memberships: { include: { user: { select: { id: true, name: true, role: true } } }, orderBy: { joinedAt: "asc" } }, posts: { include: { author: { select: { name: true } } }, orderBy: [{ pinned: "desc" }, { createdAt: "desc" }] } } });
  if (!group) notFound(); const membership = group.memberships.find(m => m.userId === user?.id); const canModerate = user?.role === Role.ADMIN || (!!membership && membership.role !== MembershipRole.MEMBER);
  return <div className="shell py-10"><Notice message={error}/><div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div><section className="card mb-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><span className="text-xs font-bold uppercase tracking-wider text-brand">{group.type === "VENUE" ? "Official venue group" : "Community"}</span><h1 className="mt-2 text-4xl font-black">{group.name}</h1>{group.venue ? <p className="mt-1 font-medium text-black/50">{group.venue.location}</p> : null}<p className="mt-4 max-w-2xl leading-7 text-black/65">{group.description}</p></div>{user ? membership ? <form action={leaveGroup}><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="slug" value={slug}/><button className="btn-secondary" disabled={membership.role !== MembershipRole.MEMBER}>{membership.role === MembershipRole.MEMBER ? "Leave group" : "Group admin"}</button></form> : <form action={joinGroup}><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="slug" value={slug}/><button className="btn">Join group</button></form> : <a href="/login" className="btn">Log in to join</a>}</div></section>
      {membership ? <form action={createPost} className="card mb-6"><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="slug" value={slug}/><label className="label" htmlFor="body">Share with the group</label><textarea className="field min-h-28 resize-y" id="body" name="body" maxLength={2000} required placeholder="What’s happening at the water?"/><div className="mt-3 flex items-center justify-between">{canModerate ? <label className="text-sm"><input type="checkbox" name="official" className="mr-2 accent-brand"/>Official update</label> : <span/>}<button className="btn">Post update</button></div></form> : null}
      <div className="space-y-4">{group.posts.length ? group.posts.map(p => <PostCard key={p.id} post={p} slug={slug} canModerate={canModerate}/>) : <div className="card text-center text-black/50">No posts yet. Be the first to share.</div>}</div></div>
      <aside><div className="card lg:sticky lg:top-6"><h2 className="text-lg font-bold">Members · {group.memberships.length}</h2><div className="mt-4 space-y-3">{group.memberships.map(m => <div key={m.id} className="flex items-center justify-between border-b border-black/5 pb-3 last:border-0"><span className="font-medium">{m.user.name}</span>{m.role !== MembershipRole.MEMBER ? <span className="text-xs font-bold uppercase text-brand">{m.role.toLowerCase()}</span> : null}</div>)}</div></div></aside></div></div>;
}
