import Link from "next/link";
import { branding } from "@/lib/branding";
import { db } from "@/lib/db";
import { GroupCard } from "@/components/ui";
export default async function Home() {
  const groups = await db.group.findMany({ take: 3, orderBy: { memberships: { _count: "desc" } }, include: { venue: { select: { location: true } }, _count: { select: { memberships: true, posts: true } } } });
  return <><section className="overflow-hidden bg-ink text-white"><div className="shell grid gap-10 py-20 md:grid-cols-[1.2fr_.8fr] md:py-28"><div><p className="mb-5 text-sm font-bold uppercase tracking-[.2em] text-emerald-300">The social home of UK angling</p><h1 className="max-w-3xl text-5xl font-black leading-[1.05] sm:text-7xl">More time fishing. Better company.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">{branding.tagline} Join anglers and fisheries, swap knowledge, follow official venue updates and share what’s happening at the water.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn !bg-white !text-ink" href="/register">Join free forever</Link><Link className="btn-secondary !border-white/25 !bg-transparent !text-white" href="/discover">Explore groups</Link></div></div><div className="hidden place-items-center md:grid"><div className="aspect-square w-full max-w-sm rounded-full border border-white/10 bg-[radial-gradient(circle_at_30%_30%,#35a97d,#176b4d_45%,#0b3528)] p-12"><div className="flex h-full items-center justify-center rounded-full border border-white/20 text-center text-2xl font-black">NO FEES<br/>NO BOOKING<br/>JUST FISHING</div></div></div></div></section>
  <section className="shell py-16"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-wider text-brand">Find your people</p><h2 className="mt-2 text-3xl font-black">Groups worth joining</h2></div><Link href="/discover" className="font-semibold text-brand">See all →</Link></div><div className="grid gap-5 md:grid-cols-3">{groups.map(g => <GroupCard key={g.id} group={g}/>)}</div></section></>;
}
