import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true, channel: "chrome", args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.goto("http://localhost:3000/login", { waitUntil: "networkidle" });
await page.fill("#email", "angler@bankside.test");
await page.fill("#password", "password123");
await Promise.all([page.waitForURL("**/feed**"), page.click('button[type="submit"]')]);
await page.waitForTimeout(500);
const like = await page.locator('button[aria-pressed]').first().textContent();
const comment = await page.locator('input[placeholder="Write a comment…"]').count();
await page.goto("http://localhost:3000/compose", { waitUntil: "networkidle" });
const composePhoto = await page.locator('#composer-image').count();
await page.goto("http://localhost:3000/discover?q=Willow", { waitUntil: "networkidle" });
const willow = await page.locator("text=Willow Lakes").count();
await page.goto("http://localhost:3000/login");
await page.fill("#email", "owner@bankside.test");
await page.fill("#password", "password123");
await Promise.all([page.waitForURL("**/feed**"), page.click('button[type="submit"]')]);
await page.goto("http://localhost:3000/owner/venues/willow-lakes", { waitUntil: "networkidle" });
const invite = await page.locator("text=Invite link").count();
const members = await page.locator("text=Members").count();
const edit = await page.locator("text=Edit venue").count();
const notices = await page.locator("text=Noticeboard").count();
await page.goto("http://localhost:3000/me/notifications", { waitUntil: "networkidle" });
const notif = await page.locator("text=commented").count();
console.log(JSON.stringify({ like, commentInputs: comment, composePhoto, willow, invite, members, edit, notices, notif }, null, 2));
await browser.close();
